# Generated by Django 2.1.7 on 2019-03-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=15, verbose_name='Celular')),
                ('sales_total', models.IntegerField(default=0, verbose_name='Total de Vendas')),
            ],
        ),
        migrations.RemoveField(
            model_name='useroffice',
            name='office',
        ),
    ]
