# Generated by Django 2.1.7 on 2019-03-12 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190312_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesman',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
    ]
