# Generated by Django 2.1.7 on 2019-03-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Preço')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('warranty', models.CharField(max_length=2, verbose_name='Garantia')),
                ('category', models.CharField(choices=[('computador', 'Computador'), ('celular', 'Celular'), ('acessorios', 'Acessórios'), ('outros', 'Outros')], default='outros', max_length=15, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
