# Generated by Django 2.0.7 on 2019-03-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190330_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.PositiveIntegerField(max_length=3, verbose_name='Garantia'),
        ),
    ]
