# Generated by Django 2.0.7 on 2019-04-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_bag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='payment',
            field=models.CharField(choices=[('cartao', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('dinheiro', 'Dinheiro')], default='dinheiro', max_length=100, verbose_name='Forma de Pagamento'),
        ),
    ]
