# Generated by Django 2.0.7 on 2019-04-23 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20190422_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='salesman',
        ),
    ]
